FROM haskell:8

RUN mkdir /Banking
WORKDIR /Banking

COPY ./ /Banking/

RUN stack setup

RUN stack install base-4.10
RUN stack install bytestring-0.10
RUN stack install cassava-0.5
RUN stack install vector-0.12
RUN stack install extra-1.6
RUN stack install HTF-0.13
RUN stack install regex-compat-0.95
RUN stack install QuickCheck
RUN stack install time
RUN stack install scotty

RUN stack ghci